import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — OilStrikeAI",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-navy">
      <Nav />
      <main className="mx-auto max-w-3xl px-6 py-16 text-white/70">
        <h1 className="font-display text-3xl font-semibold text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-white/40">Last updated: July 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="font-display text-lg font-semibold text-white">1. Agreement to Terms</h2>
            <p className="mt-2">
              These Terms of Service (&quot;Terms&quot;) govern your access to and use of OilStrikeAI (the
              &quot;Service&quot;), operated by OilStrikeAI (&quot;we,&quot; &quot;us,&quot; or
              &quot;our&quot;). By creating an account, requesting a free Discovery Audit, or otherwise
              using the Service, you agree to these Terms. If you are using the Service on behalf of a
              company, you represent that you have the authority to bind that company to these Terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">2. Description of the Service</h2>
            <p className="mt-2">
              OilStrikeAI reads oil &amp; gas contracts and billing statements you upload and uses
              artificial intelligence to identify potential billing discrepancies, contractual
              obligations, deadlines, and risk indicators. The Service also provides tools for
              delegating work among your team and tracking progress on identified items.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">3. Not Legal or Financial Advice</h2>
            <p className="mt-2">
              The Service is an analytical and organizational tool, not a substitute for professional
              legal, accounting, or financial advice. Every finding is generated by an AI model reading
              the documents you provide and may be incomplete, mistaken, or based on ambiguous language
              in the source document. You are responsible for independently verifying any finding before
              relying on it or taking action based on it, including consulting a qualified attorney or
              accountant where appropriate.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">4. Accounts and Team Members</h2>
            <p className="mt-2">
              You are responsible for maintaining the confidentiality of your account credentials and for
              all activity that occurs under your account. If you invite team members to your company&apos;s
              account, you are responsible for their compliance with these Terms and for managing their
              access, including revoking it when appropriate.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">5. Your Documents and Data</h2>
            <p className="mt-2">
              You retain all ownership rights to the documents and data you upload. You grant us a
              limited license to process, store, and analyze that content solely to provide the Service
              to you. We do not use your uploaded documents to train AI models, and we do not sell your
              data to third parties.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">6. Free Discovery Audit</h2>
            <p className="mt-2">
              The free Discovery Audit is limited to one submission per email address, and one submission
              per company per 24-hour period, to prevent abuse. We reserve the right to decline to
              process a document that is unrelated to oil &amp; gas contracts or billing, or that does not
              contain enough content to produce a meaningful analysis.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">7. Subscriptions and Billing</h2>
            <p className="mt-2">
              Paid subscriptions are billed in advance on a recurring basis through our payment processor,
              Stripe. You can manage or cancel your subscription at any time through your billing portal.
              Fees already paid are non-refundable except where required by law. We may change our pricing
              with reasonable advance notice.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">8. Acceptable Use</h2>
            <p className="mt-2">
              You agree not to: use the Service for any unlawful purpose; attempt to circumvent usage
              limits (such as the free audit limit); upload documents you do not have the right to share;
              or attempt to interfere with, reverse-engineer, or gain unauthorized access to the Service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">9. Limitation of Liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, OilStrikeAI shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the Service, including
              decisions made based on an AI-generated finding. Our total liability for any claim relating
              to the Service is limited to the amount you paid us in the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">10. Termination</h2>
            <p className="mt-2">
              You may stop using the Service and cancel your subscription at any time. We may suspend or
              terminate your access if you materially breach these Terms, including abuse of the free
              audit or attempted circumvention of usage limits.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">11. Changes to These Terms</h2>
            <p className="mt-2">
              We may update these Terms from time to time. If we make material changes, we will notify
              you by email or through the Service before they take effect.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white">12. Contact</h2>
            <p className="mt-2">
              Questions about these Terms can be sent to{" "}
              <a href="mailto:hello@oilstrikeai.com" className="text-gold hover:underline">
                hello@oilstrikeai.com
              </a>
              .
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
